### ISSUE TITLE
Name in package.json

### ISSUE THREAD

**Issue by chomamateusz** [dev0x10/aurelia-materialize#1]
It shouldn't be "aurelia-material-starter" not "Aurelia Material Starter"? When Im running npm install npm tells me that it isn't valid name and doesn't install dependences.

**Comment by dev0x10** [comment]
@AmazingDesign sorry this repo is not updated anymore. Please take a look on this one
https://github.com/Ullfis/materialize-aurelia-webpack-skeleton
